'''
[프로그래머스 SQL 고득점 KIT / JOIN]
보호소에서 중성화한 동물

-> JOIN + WHERE
'''

SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_INS AS A
JOIN ANIMAL_OUTS AS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE (A.SEX_UPON_INTAKE = 'Intact Female' AND B.SEX_UPON_OUTCOME = 'Spayed Female')
OR (A.SEX_UPON_INTAKE = 'Intact Male' AND B.SEX_UPON_OUTCOME = 'Neutered Male')