'''
[프로그래머스 SQL 고득점 KIT / JOIN]
오랜 기간 보호한 동물(1)

-> LEFT JOIN + is null + 상위 N개
'''

SELECT A.NAME, A.DATETIME
FROM ANIMAL_INS AS A
LEFT JOIN ANIMAL_OUTS AS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.ANIMAL_ID is null
ORDER BY A.DATETIME ASC
LIMIT 3